services:
  mongodb:
    container_name: reactivechat-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=reactivechat
      - MONGO_INITDB_ROOT_PASSWORD=reactivechat
    volumes:
      - mongo-data:/data/db
    command: ["--bind_ip_all"]

  mongo-express:
    container_name: reactivechat-express
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=reactivechat
      - ME_CONFIG_MONGODB_ADMINPASSWORD=reactivechat
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

volumes:
  mongo-data:
    driver: local
